# Generated by Django 5.1.7 on 2025-04-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('atomic_number', models.IntegerField()),
                ('atomic_mass', models.IntegerField()),
            ],
        ),
    ]
